NO-JIRA: Hermeto: go mod vendor (#17)
* NO-JIRA: Hermeto: go mod vendor

https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=67393988

https://download-01.beak-001.prod.iad2.dc.redhat.com/brewroot/work/tasks/3988/67393988/remote-sources.log

```
2025-04-22 09:02:11,555 INFO Vendoring the gomod dependencies
2025-04-22 09:02:22,047 ERROR vendor/modules.txt changed after vendoring:
diff --git a/vendor/modules.txt b/vendor/modules.txt
index c6c9b64..974648e 100644
--- a/vendor/modules.txt
+++ b/vendor/modules.txt
@@ -186,7 +186,6 @@ github.com/prometheus/procfs/internal/fs
 github.com/prometheus/procfs/internal/util
 # github.com/robfig/cron/v3 v3.0.1
 ## explicit; go 1.12
-github.com/robfig/cron/v3
 # github.com/sirupsen/logrus v1.9.3
 ## explicit; go 1.13
 github.com/sirupsen/logrus
2025-04-22 09:02:23,690 ERROR PackageRejected: The content of the vendor directory is not consistent with go.mod. Please check the logs for more details.
Error: PackageRejected: The content of the vendor directory is not consistent with go.mod. Please check the logs for more details.
  Please try running `go mod vendor` and committing the changes.
  Note that you may need to `git add --force` ignored files in the vendor/ dir.
  Docs: https://github.com/hermetoproject/hermeto/blob/main/docs/gomod.md#vendoring
2025/04/22 09:02:24 Skipping step because a previous step failed
```

* go mod tidy

* go mod tidy && go mod vendor

---------

Co-authored-by: Rayford Johnson <rayfordj@users.noreply.github.com>